name: homebrew-bump-debug

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        type: string
      environment:
        default: production
        type: environment
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Bump homebrew-core formula
        uses: mislav/bump-homebrew-formula-action@v3
        if: inputs.environment == 'production' && !contains(inputs.tag_name, '-')
        with:
          formula-name: gh
          tag-name: ${{ inputs.tag_name }}
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_PR_PAT }}
